### ISSUE TITLE
The results of `pc list` and `pc group list` should be displayed in alphabetical order.

### ISSUE THREAD

**Issue by SrBedrock** [SrBedrock/PluginControl#23]
Suggestion made by @SlimeDog https://github.com/SrBedrock/PluginControl/issues/3#issuecomment-1718344556

**Comment by SlimeDog** [comment]
Looks good. Note that plugin names that begin with lowercase are sorted after all plugins that start with uppercase. That is one interpretation of alphabetical order, but not the one I would choose. For example, my list includes
```
... NetworkInterceptor, PlaceholderAPI, ... Skript, ... WorldGuard, pHD, spark
```
I would prefer
```
... NetworkInterceptor, pHD, PlaceholderAPI, ... Skript, spark, ... WorldGuard
```
But it's your choice.
