### ISSUE TITLE
`pc list` should identify plugins that are in the list but not enabled -- colored red

### ISSUE THREAD

**Issue by SrBedrock** [SrBedrock/PluginControl#26]
pc list should identify plugins that are in the list but not enabled -- colored red, for example. Similarly, pc group list should identify groups for which no members are loaded.

Suggestion made by @SlimeDog https://github.com/SrBedrock/PluginControl/issues/3#issuecomment-1718344556

**Comment by SlimeDog** [comment]
Red and green works. It would be nice if I could configure the colors.
