### ISSUE TITLE
Disable doesn't seem to work

### ISSUE THREAD

**Issue by SlimeDog** [SrBedrock/PluginControl#35]
Paper 1.20.2-201
PluginControl 1.1.0 (the second one)

Since all required plugins (on my test server) have not been updated (and so are not enabled), I used `pc disable` to disable the kick feature so my test player could connect. The command reported my configured message
```
> pc disable
[16:25:26 INFO]: [PluginControl] Deactivating plugin features...
```

but the connection was still blocked.
```
[16:25:55 INFO]: Disconnecting SlimeDog: All required plugins were not loaded, so you cannot join the server!
[16:25:55 INFO]: SlimeDog lost connection: All required plugins were not loaded, so you cannot join the server!
```

Some brief experimentation suggests that`pc enable` and `pc toggle` have similar issues.

**Comment by SlimeDog** [comment]
and
- re-register the listener(s) on (re)`enable`
- handle `toggle` correctly

**Comment by SrBedrock** [comment]
@SlimeDog https://github.com/SrBedrock/PluginControl/releases/tag/v1.1.1

**Comment by SlimeDog** [comment]
Please release a jar file.

**Comment by SlimeDog** [comment]
Please post a license.

**Comment by SrBedrock** [comment]
> Please release a jar file.
> Please post a license.

Done!

**Comment by SlimeDog** [comment]
Confirmed that `pc enable`, `pc disable`, and `pc toggle` work correctly in PC 1.1.1. Thanks for fast response.
